create table if not exists public."FoodImageAnalyses" (
    id bigint generated by default as identity primary key,
    user_id bigint not null references public."Users"(id) on delete cascade,
    log_id bigint references public."DayFoodLogs"(id) on delete set null,
    food_entry_id bigint references public."FoodEntries"(id) on delete set null,
    status text not null default 'completed'
        check (status in ('completed', 'confirmed', 'failed', 'discarded')),
    user_note text
        check (user_note is null or char_length(user_note) <= 300),
    meal_name text not null,
    estimate jsonb not null,
    accepted_food jsonb,
    calories numeric(10, 1) not null check (calories >= 0),
    protein numeric(10, 1) not null check (protein >= 0),
    carbs numeric(10, 1) not null check (carbs >= 0),
    fats numeric(10, 1) not null check (fats >= 0),
    confidence numeric(4, 3) not null
        check (confidence >= 0 and confidence <= 1),
    model text not null,
    prompt_version integer not null default 1,
    input_tokens integer
        check (input_tokens is null or input_tokens >= 0),
    output_tokens integer
        check (output_tokens is null or output_tokens >= 0),
    created_at timestamptz not null default now(),
    completed_at timestamptz,
    confirmed_at timestamptz
);

create index if not exists food_image_analyses_user_created_idx
    on public."FoodImageAnalyses" (user_id, created_at desc);

create index if not exists food_image_analyses_food_entry_idx
    on public."FoodImageAnalyses" (food_entry_id)
    where food_entry_id is not null;

alter table public."FoodImageAnalyses" enable row level security;

comment on table public."FoodImageAnalyses" is
    'Stores AI nutrition estimates and confirmed values only. Meal images and image paths are never persisted.';
